
name: Run lint
on:
  workflow_dispatch:
  workflow_call:
env:
  GOPRIVATE: "github.com/mconf"
jobs:
  lint:
    name: Run lint
    runs-on: [self-hosted, ubuntu-20.04]
    steps:
    - name: Check out Source Repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.16.6

    - name: Configure Git to Access Private Modules
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Lint with GolangCI
      uses: golangci/golangci-lint-action@v5.1.0
      with:
        version: v1.44.2
