name: Run lint
on:
  workflow_call:
    inputs:
      go-version:
        type: string
        required: true
      golangci-lint-version:
        type: string
        required: true
env:
  GOPRIVATE: github.com/mconf/*
permissions:
  contents: read
jobs:
  lint:
    name: Run lint
    runs-on: [self-hosted, ubuntu-22.04]
    timeout-minutes: 15
    steps:
      - name: Check out Source Repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.go-version }}
          cache: true

      - name: Install SSH Agent
        if: ${{ env.ssh-private-key != '' }}
        env:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Configure Git to Access Private Modules
        if: ${{ env.ssh-private-key != '' }}
        env:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          version: ${{ inputs.golangci-lint-version }}
          args: --timeout=10m
