name: Run tests
on:
  workflow_dispatch:
  workflow_call:
jobs:
  Test:
    runs-on: [self-hosted, ubuntu-20.04]
    steps:
      - name: Check out Source Repository
        uses: actions/checkout@v4

      - name: Get Modified JavaScript Files
        id: changed-javascript-files
        uses: tj-actions/changed-files@v47

      - name: Setup Node.js
        if: contains(steps.changed-javascript-files.outputs.modified_files, '.js')
        uses: actions/setup-node@v6
        with:
          node-version: 12
          cache: 'npm'

      - name: Clean Install Project
        if: contains(steps.changed-javascript-files.outputs.modified_files, '.js')
        run: npm ci

      - name: Test
        if: contains(steps.changed-javascript-files.outputs.modified_files, '.js')
        run: npm test
