name: Run lint
on:
  workflow_call:
    inputs:
      SRC_PATH:
        type: string
        required: true
      python-version:
        type: string
        required: true
      black-version:
        type: string
        required: true
permissions:
  contents: read
jobs:
  format-and-lint:
    runs-on: [self-hosted, ubuntu-22.04]
    name: Lint and Check Formatting
    timeout-minutes: 15
    steps:
      - name: Check out Source Repository
        uses: actions/checkout@v6
      - name: Set up Python Environment
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: true
          cache-dependency-path: ./pdm.lock
      - name: Install Dependencies
        run: pdm install
      - name: Run Flake8 Linter
        uses: py-actions/flake8@v2
        with:
          path: "./${{ inputs.SRC_PATH }}"
          ignore: "E501,E721,W503,E203"
      - name: Check Formatting with Black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./${{ inputs.SRC_PATH }}"
          version: ${{ inputs.black-version }}
      - name: Check Import Sorting with isort
        uses: isort/isort-action@v1.1.1
        with:
          sortPaths: "./${{ inputs.SRC_PATH }}"
