name: Run lint
on:
  workflow_call:
    inputs:
      SRC_PATH:
        type: string
        required: true

jobs:
  format-and-lint:
    runs-on: [self-hosted, ubuntu-20.04]
    name: Lint and Check Formatting
    steps:
      - name: Check out Source Repository
        uses: actions/checkout@v4
      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.10"
          cache: true
          cache-dependency-path: ./pdm.lock
      - name: Install Dependencies
        run: pdm install
      - name: Lint with Flake
        uses: py-actions/flake8@v2
        with:
          path: "./${{ inputs.SRC_PATH }}"
          ignore: "E501,E721,W503"
      - name: Check with Black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./${{ inputs.SRC_PATH }}"
          version: "22.10.0"
      - name: Run Isort
        uses: isort/isort-action@v1.0.0
