name: Push new tag

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      should_push:
        type: boolean
        required: true

jobs:
  build-push-scan:
    name: Build, Push and Scan Docker
    runs-on: [self-hosted, ubuntu-20.04]
    steps:
      - name: Check out Source Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: daileon
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}

      - name: Calculate tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
          # Replace / with - to avoid conflict
            TAG=$(echo "${{ github.head_ref }}" | sed 's/\//-/g')
          else
            TAG="${{github.ref_name}}"
          fi
          echo "IMAGE=${{github.repository}}:$TAG" >> "$GITHUB_OUTPUT"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.tag.outputs.IMAGE }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.should_push }}
          load: true
          tags: ${{ steps.tag.outputs.IMAGE }}
          context: .
          platforms: linux/amd64
          build-args: |
            git_token=${{ secrets.GITHUB_TOKEN }}
          cache-from: type=registry,ref=${{ steps.tag.outputs.IMAGE }}
          cache-to: type=registry,ref=${{ steps.tag.outputs.IMAGE }},image-manifest=true,oci-mediatypes=true,mode=max
          labels: |
            ${{ steps.meta.outputs.labels }}

      - name: Generate UUID4
        id: generate-uuid
        run: echo "UUID=$(cat /proc/sys/kernel/random/uuid)" >> "$GITHUB_ENV"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.tag.outputs.IMAGE }}
          ignore-unfixed: true
          format: "json"
          output: "${{ env.UUID }}.json"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy results to Trivy Explorer
        run: |
          curl -H "Content-Type: application/json" -H "Authorization: ${{secrets.TRIVY_EXPLORER_AUTH_TOKEN}}" --data "${{ env.UUID }}.json" ${{secrets.TRIVY_EXPLORER_URL}}
          echo
