name: Run trivy on filesystem
on:
  workflow_dispatch:
  workflow_call:
jobs:
  trivy:
    name: Run trivy check
    runs-on: [self-hosted, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        id: trivy-scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "table"
          severity: "CRITICAL,HIGH"

      - name: Post Trivy results as a comment
        uses: actions/github-script@v5
        with:
          script: |
            const results = ${{ steps.trivy-scan.outputs.stdout }}
            const prNumber = context.payload.pull_request.number
            const octokit = github.getOctokit(token)
            octokit.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `Trivy scan results:\n\`\`\`\n${results}\n\`\`\``
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
